### ISSUE TITLE
Finish milestone

### ISSUE THREAD

**Issue by sagacity** [datatrash/mos#162]
* [x] Document unit testing
* [x] Document markdown comments hover
* [x] Double-check formatting option documentation
* [x] Perform release
* [x] Perform VS Code release

**Comment by sagacity** [comment]
Release done! Closes #165 as well.
